# Generated by Django 5.0.3 on 2024-04-04 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=50)),
                ('userType', models.CharField(choices=[('Admin', 'Admin'), ('PM', 'Project-Manager'), ('TL', 'Team-Leader'), ('Emp', 'Employee')], max_length=100)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=50)),
                ('projectDescription', models.CharField(max_length=500)),
                ('projectStartDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
