# Generated by Django 5.0.3 on 2024-04-04 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectCreator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.customuser'),
            preserve_default=False,
        ),
    ]
