# Generated by Django 5.0.3 on 2024-04-15 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectallocation',
            name='taskDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='taskEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='taskName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='taskStartDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='taskStatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
