# Generated by Django 5.0.3 on 2024-04-16 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_projectallocation_taskstartdate_manageleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageleave',
            name='leaveType',
            field=models.CharField(choices=[('half-day', 'half-day'), ('full-day', 'full-day')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manageleave',
            name='empName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
