# Generated by Django 5.0.3 on 2024-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Project-Manager', 'Project-Manager'), ('Team-Leader', 'Team-Leader'), ('Employee', 'Employee')], max_length=100),
        ),
    ]
