# Generated by Django 5.0.3 on 2024-04-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
