# Generated by Django 5.0.3 on 2024-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_manageleave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageleave',
            name='leaveType',
            field=models.CharField(choices=[('half-day', 'half-day'), ('full-day', 'full-day')], default=['full-day'], max_length=100),
        ),
    ]
