# Generated by Django 5.0.3 on 2024-04-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_username_customuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='toDo',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
