# Generated by Django 5.0.3 on 2024-04-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_manageleave_approveleave_salary_salarypayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
