# Generated by Django 5.0.4 on 2024-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_salarypayment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_salary_percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='manageleave',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
    ]
